apiVersion: network.sodev.cc/v1
kind: AutoIngress
metadata:
  name: tangx-in
  namespace: k8s-auto-ingress-operator-system
  annotations:
    kubernetes.io/ingress.class: nginx

spec:
  rootDomain: tangx.in 
  servicePrefixes:
    - "web-"
    - "srv-"
  tlsSecretName: "wild-tangx-in"
